export const especialidades = [
  {
    codigo: 716,
    especialidade: 'Acupuntura',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 717,
    especialidade: 'Alergia e Imunologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 787,
    especialidade: 'Alergia e Imunologia Pediátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 501,
    especialidade: 'Análises Clínicas',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 502,
    especialidade: 'Anatomia Patológica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 756,
    especialidade: 'Anatomia Patologica / Citopatologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 632,
    especialidade: 'Anestesiologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 621,
    especialidade: 'Angiografia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 718,
    especialidade: 'Angiologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 704,
    especialidade: 'Angioressonancia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 705,
    especialidade: 'Angiotomografia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 753,
    especialidade: 'Artroscopia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 719,
    especialidade: 'Atendimento Ao Queimado',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 504,
    especialidade: 'Audiometria',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 706,
    especialidade: 'Broncoscopia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 720,
    especialidade: 'Cancerologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 721,
    especialidade: 'Cancerologia Pediatrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 722,
    especialidade: 'Cardiologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 786,
    especialidade: 'Cardiologia Fetal',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 793,
    especialidade: 'Cardiologia Pediátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 815,
    especialidade: 'Cirurgia Bariátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 506,
    especialidade: 'Cirurgia Buco-Maxilo-Facial',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 634,
    especialidade: 'Cirurgia Cardiaca',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 723,
    especialidade: 'Cirurgia Cardiovascular',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 724,
    especialidade: 'Cirurgia Cranio Maxilo Facial',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 785,
    especialidade: 'Cirurgia da Cabeça e Pescoço',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 725,
    especialidade: 'Cirurgia Da Coluna',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 707,
    especialidade: 'Cirurgia da Mão',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 507,
    especialidade: 'Cirurgia de Miopia (Método Lasik/PRK)',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 708,
    especialidade: 'Cirurgia do Aparelho Digestivo',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 726,
    especialidade: 'Cirurgia Do Trauma',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 727,
    especialidade: 'Cirurgia Geral',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 995,
    especialidade: 'Cirurgia Oncológica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 784,
    especialidade: 'Cirurgia Pediátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 728,
    especialidade: 'Cirurgia Plastica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 783,
    especialidade: 'Cirurgia Torácica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 729,
    especialidade: 'Cirurgia Vascular',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 508,
    especialidade: 'Citopatologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 754,
    especialidade: 'Clínica Médica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 709,
    especialidade: 'Colonoscopia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 730,
    especialidade: 'Coloproctologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 510,
    especialidade: 'Colpocitologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 511,
    especialidade: 'Colposcopia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 546,
    especialidade: 'Densitometria Óssea',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 731,
    especialidade: 'Dermatologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 692,
    especialidade: 'Dermatologia Infantil',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 547,
    especialidade: 'Diálise (Hemodiálise)',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 623,
    especialidade: 'Ecocardiografia (Ecocardiograma)',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 757,
    especialidade: 'Ecocardiografia Fetal',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 758,
    especialidade: 'Ecografia Vascular Com Doppler',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 549,
    especialidade: 'Eletrocardiograma',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 792,
    especialidade: 'Eletrocardiograma Pediátrico',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 550,
    especialidade: 'Eletroencefalografia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 551,
    especialidade: 'Eletroneuromiografia/Eletromiografia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 759,
    especialidade: 'Endocrinologia E Metabologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 760,
    especialidade: 'Endocrinologia Pediatrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 855,
    especialidade: 'Endoscopia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 791,
    especialidade: 'Endoscopia das Vias Digestivas',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 710,
    especialidade: 'Escleroterapia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 614,
    especialidade: 'Espirometria',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 732,
    especialidade: 'Fisiatria',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 555,
    especialidade: 'Fisioterapia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 688,
    especialidade: 'Fonoaudiologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 755,
    especialidade: 'Fototerapia (PUVA)',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 733,
    especialidade: 'Gastroenterologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 781,
    especialidade: 'Gastroenterologia Pediátrica ',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 761,
    especialidade: 'Genetica Medica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 734,
    especialidade: 'Geriatria',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 780,
    especialidade: 'Ginecologia e Obstetrícia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 735,
    especialidade: 'Ginecologia Pediatrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 736,
    especialidade: 'Hematologia E Hemoterapia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 737,
    especialidade: 'Hematologia E Hemoterapia Pediatrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 558,
    especialidade: 'Hemodinâmica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 559,
    especialidade: 'Hemoterapia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 738,
    especialidade: 'Hepatologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 762,
    especialidade: 'Histeroscopia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 560,
    especialidade: 'Holter 24 horas',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 739,
    especialidade: 'Homeopatia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 779,
    especialidade: 'Homeopatia Pediátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 110,
    especialidade: 'Hospital Dia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 112,
    especialidade: 'Hospital Especializado em Cardiologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 895,
    especialidade: 'Hospital Especializado em Cirurgia Bariátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 133,
    especialidade: 'Hospital Especializado em Cirurgia Cabeça e Pescoço',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 134,
    especialidade: 'Hospital Especializado em Cirurgia da Mão',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 132,
    especialidade: 'Hospital Especializado em Cirurgia Plástica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 135,
    especialidade: 'Hospital Especializado em Cirurgia Torácica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 136,
    especialidade: 'Hospital Especializado em Cirurgia Vascular',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 118,
    especialidade: 'Hospital Especializado em Crânio Maxilo facial',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 123,
    especialidade: 'Hospital Especializado em Doenças Infectocontagiosas',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 130,
    especialidade: 'Hospital Especializado em Endocrinologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 124,
    especialidade: 'Hospital Especializado em Gastroenterologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 126,
    especialidade: 'Hospital Especializado em Geriatria',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 127,
    especialidade: 'Hospital Especializado em Hematologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 125,
    especialidade: 'Hospital Especializado em Hepatologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 119,
    especialidade: 'Hospital Especializado em Neurologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 113,
    especialidade: 'Hospital Especializado em Oftalmologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 114,
    especialidade: 'Hospital Especializado em Oncologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 115,
    especialidade: 'Hospital Especializado em Ortopedia / Traumatologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 116,
    especialidade: 'Hospital Especializado em Otorrinolaringologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 117,
    especialidade: 'Hospital Especializado em Pediatria',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 128,
    especialidade: 'Hospital Especializado em Pneumologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 131,
    especialidade: 'Hospital Especializado em Proctologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 121,
    especialidade: 'Hospital Especializado em Psiquiatria',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 122,
    especialidade: 'Hospital Especializado em Queimados',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 129,
    especialidade: 'Hospital Especializado em Reumatologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 120,
    especialidade: 'Hospital Especializado em Urologia/Nefrologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 109,
    especialidade: 'Hospital Geral',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 562,
    especialidade: 'Impedânciometria',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 740,
    especialidade: 'Infectologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 711,
    especialidade: 'Infectologia Pediatrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 790,
    especialidade: 'Laringoscopia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 564,
    especialidade: 'Líquor',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 770,
    especialidade: 'Litotripsia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 566,
    especialidade: 'Mamografia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 767,
    especialidade: 'MAPA',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 567,
    especialidade: 'Mapeamento Cerebral',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 741,
    especialidade: 'Mastologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 111,
    especialidade: 'Maternidade',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 996,
    especialidade: 'Medicina de Emergência',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 915,
    especialidade: 'Medicina De Família E Comunidade',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 1004,
    especialidade: 'Medicina de Tráfego',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 997,
    especialidade: 'Medicina do Trabalho',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 998,
    especialidade: 'Medicina do Tráfego',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 999,
    especialidade: 'Medicina Esportiva',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 875,
    especialidade: 'Medicina Física e Reabilitação',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 1000,
    especialidade: 'Medicina Intensiva',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 1001,
    especialidade: 'Medicina Legal e Perícia Médica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 568,
    especialidade: 'Medicina Nuclear',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 1002,
    especialidade: 'Medicina Preventiva e Social',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 955,
    especialidade: 'Método ABA',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 956,
    especialidade: 'Método Bobath',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 957,
    especialidade: 'Método Cuevas Medek Exercises',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 958,
    especialidade: 'Método PECS',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 960,
    especialidade: 'Método Teacch/ Denver',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 742,
    especialidade: 'Nefrologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 778,
    especialidade: 'Nefrologia Pediátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 743,
    especialidade: 'Neonatologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 777,
    especialidade: 'Neurocirurgia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 619,
    especialidade: 'Neurofisiologia clinica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 744,
    especialidade: 'Neurologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 776,
    especialidade: 'Neurologia Pediátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 594,
    especialidade: 'Nutrição',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 745,
    especialidade: 'Nutrologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 746,
    especialidade: 'Nutrologia Pediatrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 747,
    especialidade: 'Oftalmologia',
    subespecialidade: [
      {
        codigo: '7478',
        descricao: 'Órbita',
      },
      {
        codigo: '7473',
        descricao: 'Glaucoma',
      },
      {
        codigo: '7475',
        descricao: 'Estrabismo',
      },
      {
        codigo: '7474',
        descricao: 'Refrativa',
      },
      {
        codigo: '7476',
        descricao: 'Plástica',
      },
      {
        codigo: '7471',
        descricao: 'Catarata',
      },
      {
        codigo: '9999',
        descricao: 'Geral',
      },
      {
        codigo: '7472',
        descricao: 'Retina',
      },
      {
        codigo: '7477',
        descricao: 'Visão Sub Normal',
      },
    ],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 661,
    especialidade: 'Oncologia Cirúrgica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 662,
    especialidade: 'Oncologia Clinica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 663,
    especialidade: 'Oncologia Pediátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 748,
    especialidade: 'Ortopedia  E Traumatologia',
    subespecialidade: [
      {
        codigo: '7484',
        descricao: 'Quadril',
      },
      {
        codigo: '7486',
        descricao: 'Tornozelo e pe',
      },
      {
        codigo: '7482',
        descricao: 'Coluna',
      },
      {
        codigo: '7487',
        descricao: 'Tumor Osseo',
      },
      {
        codigo: '7485',
        descricao: 'Joelho',
      },
      {
        codigo: '7488',
        descricao: 'Ortopedia Infantil',
      },
      {
        codigo: '7481',
        descricao: 'Ombro',
      },
      {
        codigo: '9999',
        descricao: 'Geral',
      },
      {
        codigo: '7483',
        descricao: 'Cotovelo/Mao',
      },
    ],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 696,
    especialidade: 'Ortopedia Pediátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 749,
    especialidade: 'Otorrinolaringologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 713,
    especialidade: 'Otorrinolaringologia Pediatrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 789,
    especialidade: 'Patologia clínica / Medicina Laboratorial ',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 775,
    especialidade: 'Pediatria',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 572,
    especialidade: 'Peniscopia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 714,
    especialidade: 'Pet Dedicado Oncologico',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 750,
    especialidade: 'Pneumologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 697,
    especialidade: 'Pneumologia Pediátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 615,
    especialidade: 'Polissonografia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 751,
    especialidade: 'Proctologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 104,
    especialidade: 'Pronto Socorro Adulto',
    subespecialidade: [],
    urgenciaEmergencia: true,
    ordemExibicaoEmergencia: '1',
  },
  {
    codigo: 103,
    especialidade: 'Pronto Socorro Cardiologia',
    subespecialidade: [],
    urgenciaEmergencia: true,
    ordemExibicaoEmergencia: '8',
  },
  {
    codigo: 975,
    especialidade: 'Pronto Socorro Geral',
    subespecialidade: [],
    urgenciaEmergencia: true,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 768,
    especialidade: 'Pronto Socorro Ginecologia',
    subespecialidade: [],
    urgenciaEmergencia: true,
    ordemExibicaoEmergencia: '7',
  },
  {
    codigo: 769,
    especialidade: 'Pronto Socorro Obstetrícia',
    subespecialidade: [],
    urgenciaEmergencia: true,
    ordemExibicaoEmergencia: '3',
  },
  {
    codigo: 700,
    especialidade: 'Pronto Socorro Oftalmologia',
    subespecialidade: [],
    urgenciaEmergencia: true,
    ordemExibicaoEmergencia: '6',
  },
  {
    codigo: 105,
    especialidade: 'Pronto Socorro Ortopedia',
    subespecialidade: [],
    urgenciaEmergencia: true,
    ordemExibicaoEmergencia: '4',
  },
  {
    codigo: 106,
    especialidade: 'Pronto Socorro Otorrinolaringologista',
    subespecialidade: [],
    urgenciaEmergencia: true,
    ordemExibicaoEmergencia: '5',
  },
  {
    codigo: 107,
    especialidade: 'Pronto Socorro Pediatria',
    subespecialidade: [],
    urgenciaEmergencia: true,
    ordemExibicaoEmergencia: '2',
  },
  {
    codigo: 108,
    especialidade: 'Pronto Socorro Psiquiatria',
    subespecialidade: [],
    urgenciaEmergencia: true,
    ordemExibicaoEmergencia: '9',
  },
  {
    codigo: 573,
    especialidade: 'Prova de Função Pulmonar',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 763,
    especialidade: 'Prova Ventilatoria Completa',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 689,
    especialidade: 'Psicologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 575,
    especialidade: 'Psicoterapia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 774,
    especialidade: 'Psiquiatria',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 576,
    especialidade: 'Quimioterapia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 577,
    especialidade: 'Radiodiagnóstico',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 1003,
    especialidade: 'Radiologia e Diagnóstico por Imagem',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 629,
    especialidade: 'Radiologia intervencionista',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 579,
    especialidade: 'Radioterapia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 582,
    especialidade: 'Ressonância Magnética',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 773,
    especialidade: 'Reumatologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 772,
    especialidade: 'Reumatologia Pediátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 671,
    especialidade: 'RPG',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 703,
    especialidade: 'Terapia Ocupacional',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 715,
    especialidade: 'Teste Alergico - Contato',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 788,
    especialidade: 'Teste do Pezinho',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 583,
    especialidade: 'Teste Ergométrico',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 764,
    especialidade: 'Tilt Test',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 765,
    especialidade: 'Tococardiograma Fetal',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 585,
    especialidade: 'Tomografia Computadorizada',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 794,
    especialidade: 'Tratamento da Dor Cronica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 586,
    especialidade: 'Ultrassonografia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 701,
    especialidade: 'Ultrassonografia Ocular ',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 752,
    especialidade: 'Urologia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 771,
    especialidade: 'Urologia Pediátrica',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 631,
    especialidade: 'Videolaparoscopia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
  {
    codigo: 588,
    especialidade: 'Vulvoscopia',
    subespecialidade: [],
    urgenciaEmergencia: false,
    ordemExibicaoEmergencia: null,
  },
];

export const qualificacoes = [
  {
    codigo: 13,
    descricao: 'I - Certificação ISO 9001',
  },
  {
    codigo: 14,
    descricao: 'G - Certificações de Entidades Gestoras de Outros Programas de Qualidade',
  },
  {
    codigo: 6,
    descricao: 'N  -  Comunicação de Eventos Adversos',
  },
  {
    codigo: 15,
    descricao: 'M - Mestrado',
  },
  {
    codigo: 12,
    descricao: 'D - Doutorado / Pós-Doutorado',
  },
  {
    codigo: 7,
    descricao: 'P - Pós graduação latu senso',
  },
  {
    codigo: 8,
    descricao: 'R - Residência',
  },
  {
    codigo: 11,
    descricao: 'A - Programa de Acreditação',
  },
  {
    codigo: 10,
    descricao: 'Q  -  Qualidade Monitorada',
  },
  {
    codigo: 9,
    descricao: 'E  -  Título de Especialista',
  },
];
